### ISSUE TITLE
Move away from blacklist and whitelist

### ISSUE THREAD

**Issue by lupino3** [microsoft/PowerShell-FeatureFlags#19]
We should move from `blacklist` to `denylist` and from `whitelist` to `allowlist`.

The existing words are unnecessarily loaded with racist weight.

**Comment by blacklistisnotracist** [comment]
I do agree allowlist/denylist may be better terms because they are more descriptive. That being said, calling blacklist or whitelist a racist word is simply wrong.

First, blacklist's origins have nothing to do with black people. What's more, it has never been used as an abusive word against black people. It's only a certain group of extreme non-black liberals who find the word offensive and try to make them look like it has racist connotations. It's as ridiculous as people who think wearing Chinese clothes is offensive for Chinese people unless they are worn by Chinese people.

Black, as a color, carries negative connotations across many cultures. It's so embedded that hunting down every word from every language is almost impossible and meaningless.

Let's stop calling a group of people black first. Let's start from there. Color comes first, race came later. Colors are tied to images, which can't be changed.

Let's stop the hypocrisy and focus on something that have real impacts.

**Comment by lupino3** [comment]
Do you have any reference for your claim that it was "never used as an abusive word against black people"? Or that the "origins have nothing to do with black people?"

Because there is etymological research that states the opposite: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6148600/. Quote:

> it is worth examining the origins of the term “blacklist” from the Douglas Harper Etymology Dictionary, which states that its origin and history is:

> "Blacklist" also black-list, black list, “list of persons who have incurred suspicion,” 1610s, from black (adj.), here indicative of disgrace, censure, punishment (attested from 1590s, in black book) + list (n.). Specifically of employers’ list of workers considered troublesome (usually for union activity) is from 1888. As a verb, from 1718. Related: Blacklisted; blacklisting. [32]

> It is notable that the first recorded use of the term occurs at the time of mass enslavement and forced deportation of Africans to work in European-held colonies in the Americas.

That being said, do you have any interest in this software? Are there any more pressing issues you'd like me to address instead of this migration? What's the "more impactful" work you are referring to?

Thanks for bringing this up on my priority list, I'll make sure to finish the migration as soon as I have time.

**Comment by blacklistisnotracist** [comment]
@lupino3 

Do you really have PhD? That argument of the paper is based only on subjective speculations. It didn't prove anything. Just because it's on gov website, it doesn't mean it's valid.

Is there any data or reference that blacklist is actually used in the racist context? Do you really think black people are offended by this? If so, based on what?

**Comment by blacklistisnotracist** [comment]
I support this change. Meanings will be clearer. So please go ahead but bringing up racism is simply wrong and ridiculous.

**Comment by lupino3** [comment]
I have a PhD but luckily it's not needed to understand why those terms may be offensive. You are right, as a cis white male I have no first-hand experience of this kind of oppression and I can only imagine that people may find the term offensive.

This will not solve racism. This will weaken the association of "black" == "bad" and "white" == "good", which is one of the problems we face with racism.

Your arguments made sense, IF we were not living in a racist society such as the one we are in today. No reason to associate the color black, with negative meanings, with people whose color of the skin is black, and transfer those negative meanings. But unfortunately, we live in a racist society and we do apply that transfer of meaning.

That's why I want to enact this very small change. It's definitely not solving a problem and only just a symbolic change.

**Comment by blacklistisnotracist** [comment]
I recommend you watch this video: https://www.youtube.com/watch?v=GNXm7juuM-8

Yellow people will never be offended by yellow traffic light or yellow cards. Native Americans are not offended by red flags, red cards, etc.

Black is tied to darkness. Darkness always carries negative connotations because we fear enemies in the darkness at night. It's inevitable as a diurnal animal.

Going by your logic, it's a racist thing to do to illustrate villains with black color. Black magic is also a racist word. Black hat hackers, black market, etc. everything with colors would be a racist word, which is totally wrong. If you want to start a movement to call out that The White House is abusive, then go ahead and repaint the building but I think it's ridiculous.

It makes more sense to stop calling a group of people black. African people's skin is not actually black at all anyways.

**Comment by blacklistisnotracist** [comment]
It's funny that people are still identifying themselves with a color in the US. That's why people will never get over with the racism. The existence of labels always reinforces the labeling and stereotypes. Nationalism movement always starts because they identify themselves as a national of that nation. It's that simple.

I do support changing blacklist/whitelist to some other more descriptive words, because they're more descriptive. But never because of they have racist connotations. Mentioning to racism is always unnecessary. I understand your action is based on good conscience, and that's a good thing to do.
